CREATE DATABASE `Attendance_System`;

USE `Attendance_System`;

CREATE TABLE Teachers_Login (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CNIC VARCHAR(15) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Students_Login  (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CNIC VARCHAR(15) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL
);
INSERT INTO Teachers_Login(CNIC, Password) VALUES ("Abrar","123"),("38201-2247241-9","123");