CREATE TABLE employees (
    emp_code VARCHAR(15) NOT NULL PRIMARY KEY,
    cnic VARCHAR(15) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL,
    date_of_joining DATE NOT NULL,
    department VARCHAR(50) NOT NULL,
    designation VARCHAR(50) NOT NULL,
    qualification VARCHAR(100),
    specialization VARCHAR(100),
    mobile_no VARCHAR(15) NOT NULL,
    address VARCHAR(255) NOT NULL,
    salary DECIMAL(10,2) NOT NULL,
    active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO employees (
    emp_code,
    cnic,
    first_name,
    last_name,
    gender,
    email,
    date_of_birth,
    date_of_joining,
    department,
    designation,
    qualification,
    specialization,
    mobile_no,
    address,
    salary,
    is_active
) VALUES (
    'CS-FAC-101',
    '38201-224724-19',
    'Muhammad',
    'Huzaifa Awan',
    'Male',
    'huzaifa.cs@numl.edu',
    '1980-05-15',
    '2015-08-01',
    'Computer Science',
    'Assistant Professor',
    'PhD in Computer Science',
    'Software Engineering',
    '0307-1234567',
    'House #123, Street #4, Academic Colony, University Road',
    150000.00,
    1
);